// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDinVMcxUmpUOZwQp9qlHrTT91_xyUySoA',
    appId: '1:849075968130:web:cb69dea0cf038c055fbc9b',
    messagingSenderId: '849075968130',
    projectId: 'prm-lab-a2526',
    authDomain: 'prm-lab-a2526.firebaseapp.com',
    storageBucket: 'prm-lab-a2526.firebasestorage.app',
    measurementId: 'G-2RS1TQ97MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaHneR2Lo8kpKwt1TBsKK_ENJnv3zTurg',
    appId: '1:849075968130:android:c7947f4432602cb05fbc9b',
    messagingSenderId: '849075968130',
    projectId: 'prm-lab-a2526',
    storageBucket: 'prm-lab-a2526.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpKnTH-TYQK36jedKXyDNUIDznO0_vcCY',
    appId: '1:849075968130:ios:232493f67917df185fbc9b',
    messagingSenderId: '849075968130',
    projectId: 'prm-lab-a2526',
    storageBucket: 'prm-lab-a2526.firebasestorage.app',
    androidClientId: '849075968130-l332ee4lcqr6t4ukpqc17cemb6nc6v22.apps.googleusercontent.com',
    iosClientId: '849075968130-s0o4q1vogtmceuq4ndom43mln9enji31.apps.googleusercontent.com',
    iosBundleId: 'com.example.journalTrend',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpKnTH-TYQK36jedKXyDNUIDznO0_vcCY',
    appId: '1:849075968130:ios:232493f67917df185fbc9b',
    messagingSenderId: '849075968130',
    projectId: 'prm-lab-a2526',
    storageBucket: 'prm-lab-a2526.firebasestorage.app',
    androidClientId: '849075968130-l332ee4lcqr6t4ukpqc17cemb6nc6v22.apps.googleusercontent.com',
    iosClientId: '849075968130-s0o4q1vogtmceuq4ndom43mln9enji31.apps.googleusercontent.com',
    iosBundleId: 'com.example.journalTrend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDinVMcxUmpUOZwQp9qlHrTT91_xyUySoA',
    appId: '1:849075968130:web:791054ea4a4eb1905fbc9b',
    messagingSenderId: '849075968130',
    projectId: 'prm-lab-a2526',
    authDomain: 'prm-lab-a2526.firebaseapp.com',
    storageBucket: 'prm-lab-a2526.firebasestorage.app',
    measurementId: 'G-9M7D3X41E7',
  );
}
