// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCudaDmI2drHslkMoapz63ETkwdH_STuKk',
    appId: '1:62411371672:web:591344e093f86cdc074ced',
    messagingSenderId: '62411371672',
    projectId: 'prm393-3447c',
    authDomain: 'prm393-3447c.firebaseapp.com',
    storageBucket: 'prm393-3447c.firebasestorage.app',
    measurementId: 'G-J7DYRB9ZH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcMjnUwwVzg073nyiMfLYpBU-qkdeMLBU',
    appId: '1:62411371672:android:9c9f880ae7b1d24d074ced',
    messagingSenderId: '62411371672',
    projectId: 'prm393-3447c',
    storageBucket: 'prm393-3447c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTk6YHZig4NrOW2tOaULNLXMBG6r7-x7E',
    appId: '1:62411371672:ios:27da9c6984dca167074ced',
    messagingSenderId: '62411371672',
    projectId: 'prm393-3447c',
    storageBucket: 'prm393-3447c.firebasestorage.app',
    iosBundleId: 'com.example.journalTrend',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTk6YHZig4NrOW2tOaULNLXMBG6r7-x7E',
    appId: '1:62411371672:ios:27da9c6984dca167074ced',
    messagingSenderId: '62411371672',
    projectId: 'prm393-3447c',
    storageBucket: 'prm393-3447c.firebasestorage.app',
    iosBundleId: 'com.example.journalTrend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCudaDmI2drHslkMoapz63ETkwdH_STuKk',
    appId: '1:62411371672:web:b2f0d35c42a36ab5074ced',
    messagingSenderId: '62411371672',
    projectId: 'prm393-3447c',
    authDomain: 'prm393-3447c.firebaseapp.com',
    storageBucket: 'prm393-3447c.firebasestorage.app',
    measurementId: 'G-M15ZZMVNY1',
  );
}
