// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOG5jufsJ-MPnxQbvPWN0jG6IBVWEjWns',
    appId: '1:865302042692:web:14f2a09827779c89380411',
    messagingSenderId: '865302042692',
    projectId: 'journal-trend-86de9',
    authDomain: 'journal-trend-86de9.firebaseapp.com',
    storageBucket: 'journal-trend-86de9.firebasestorage.app',
    measurementId: 'G-950T46YFGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhKP8MsXlVlMP_RiatXiDi-ham15nm7s4',
    appId: '1:865302042692:android:7dc44d69c05c7733380411',
    messagingSenderId: '865302042692',
    projectId: 'journal-trend-86de9',
    storageBucket: 'journal-trend-86de9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOQBIR7Aa3qyLWcRTU0mMXhk9fbfOs9fE',
    appId: '1:865302042692:ios:57fc2dfc632ccf12380411',
    messagingSenderId: '865302042692',
    projectId: 'journal-trend-86de9',
    storageBucket: 'journal-trend-86de9.firebasestorage.app',
    iosBundleId: 'com.example.journalTrend',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOQBIR7Aa3qyLWcRTU0mMXhk9fbfOs9fE',
    appId: '1:865302042692:ios:57fc2dfc632ccf12380411',
    messagingSenderId: '865302042692',
    projectId: 'journal-trend-86de9',
    storageBucket: 'journal-trend-86de9.firebasestorage.app',
    iosBundleId: 'com.example.journalTrend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOG5jufsJ-MPnxQbvPWN0jG6IBVWEjWns',
    appId: '1:865302042692:web:2f36e4e0036f986b380411',
    messagingSenderId: '865302042692',
    projectId: 'journal-trend-86de9',
    authDomain: 'journal-trend-86de9.firebaseapp.com',
    storageBucket: 'journal-trend-86de9.firebasestorage.app',
    measurementId: 'G-6E0SN48EEQ',
  );
}
